export const API_USAGE_QUEUE = 'api-usage-events';
export const RECORD_API_USAGE_JOB = 'record-api-usage';

export interface RecordApiUsageJobData {
  /** Generated by the producer at enqueue time, reused as both the
   * ApiUsageEvent primary key and the BullMQ jobId — the same
   * idempotency mechanism click events use (see
   * links/queue/click-event.types.ts). */
  eventId: string;
  workspaceId: string;
  apiKeyId: string;
  endpoint: string;
  method: string;
  statusCode: number;
  durationMs?: number;
}
