export const CLICK_EVENT_QUEUE = 'link-clicks';
export const RECORD_CLICK_JOB = 'record-click';

export interface RecordClickJobData {
  /**
   * Generated by the producer at enqueue time (not by the database) and
   * reused as both the ClickEvent primary key AND the BullMQ jobId. This
   * is what makes processing idempotent: if this job is retried (after a
   * crash mid-processing, a transient DB error, ...), the processor
   * attempts to insert a row with this SAME id, which fails on the
   * unique-key constraint rather than creating a duplicate — see
   * analytics/processors/click-event.processor.ts.
   */
  eventId: string;
  linkId: string;
  workspaceId: string;
  occurredAt: string; // ISO string — job payloads are serialized to JSON

  /**
   * Transient inputs only — never persisted as-is. ipAddress is consumed
   * solely to compute a salted visitor hash and a geo lookup, then
   * discarded; the raw value never reaches any table (see ClickEvent,
   * which has no ipAddress column, and VisitorHashService).
   */
  ipAddress?: string;
  userAgent?: string;
  referer?: string;
  /** Raw query string from the redirect request — only recognized
   * marketing params (utm_*) are ever extracted from it and persisted. */
  queryString?: string;
}
